import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ContextWrapper from "@/lib/ContextWrapper";

const figTree = Figtree({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${figTree.className} bg-[#F9F6F4] text-[#303030]`}
    >
      <body className="p-5 h-screen">
        <ContextWrapper>
          <Header />
          {children}
        </ContextWrapper>
      </body>
    </html>
  );
}
